[project]
name = "self-signed-ca"
version = "0.0.1"
description = ""
authors = [
    {name = "Evin Dunn <@evindunn>"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography (>=46.0.5)",
    "tzdata (>=2026.2)"
]

[project.scripts]
ssca = 'self_signed_ca.ca:main'
ssc = 'self_signed_ca.cert:main'


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest-cov (>=7.1.0,<8.0.0)",
    "pytest (>=9.0.3,<10.0.0)"
]

[tool.poetry.group.dev]
optional = true

[tool.pytest.ini_options]
addopts = "--cov=self_signed_ca --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "__init__.py"
]
