name: CI

on:
  push:
    paths: &changed-files
      - self_signed_ca/**
      - pyproject.toml
      - .github/workflows/ci.yml
  pull_request:
    paths: *changed-files

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: 'evindunn/poetry:latest'
      env:
        POETRY_CACHE_DIR: ~/.cache/poetry

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - uses: actions/cache@v5
        with:
          path: ~/.cache/poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies
        run: poetry install --with=dev

      - name: Test
        run: poetry run pytest

    #   - name: E2E
    #     run: bash e2e.sh
